rizafahmi/carikerja

- src/data/employer.js
Add Citra Digital in employer list
> Add Citra Digital

- src/data/employer.js
new entry for Jabar Digital Service
> add jabar digital service

- src/data/employer.js
Add new opening for Dicoding Indonesia.
> Add Dicoding as employer

- README.md
- src/routes/index.svelte
I added ability to input multi social media. Documentation in readme updated for how to use it.
> add ability to input multi social media

- src/routes/index.svelte
Hi, i adding some tech badge and html class filter to avoid uppercase characters
> add tech badge color and html class filter

- src/data/people.js
> Bahyu sanciko profile

- src/data/employer.js
Adding new entry in hiring employer, Kitabisa with link to career page in Urbanhire
> Add Kitabisa in employer.js

- src/data/people.js
> Add Rikki Novar profile

- src/data/employer.js
> Add Warung Pintar

- src/data/employer.js
Menambahkan eFishery sebagai salah satu Perusahaan yang masih membuka lowongan pekerjaan, terutama di Bandung
> feat(employers): add efishery

- src/data/people.js
> Add Ilham Bintang

- src/routes/index.svelte
Menambahkan filter lokasi supaya memudahkan orang-orang yang ingin me-rekrut teman - teman developer sesuai dengan lokasi yang diinginkan.
> Filter dengan lokasi

- src/data/employer.js
> add xendit as employer

- src/data/people.js
> update data lokasi dan blog saya

- src/data/people.js
Hallo mas Riza, izin fork dan contrib ya
> adding me to list in people.js

- src/data/employer.js
hi, please help me to review these additions on `line 128` until `line 134` thank you
> add hiring boer-technology

- src/routes/index.svelte
Closes #92 
Add function for generate badge style
> Feat: add function for generate badge style

- src/routes/index.svelte
pr untuk issue #26 
saya juga menemukan Uncaught TypeError yang disebabkan `tech.toLowerCase()` mengakses value undefined
dan duplikasi data job seeker
> filter only unhired one and remove duplicate data, enhance sort by name

- src/data/employer.js
Add Bobobox as a hiring employer
> feat(employer.js): :sparkles: add Bobobox as hiring employer

- package-lock.json
- package.json
Pindahkan svelte-select ke devDependencies sesuai rekomendasi library: https://github.com/rob-balfre/svelte-select#installation
> fix #138 error 500 svelte-select

- src/data/people.js
Mas @Fadhila36 ini saya bikin Pull Request dari awal ya, berdasarkan data dari Pull Request #137. Soalnya yg pull request terakhir masih banyak konfliknya 🙏 
Mohon bantuan dicek apakah datanya sudah tepat atau belum
> Add data Muhammad Fadhila Abiyyu Faris

- src/data/people.js
I want to add new data about me in data people who are open to finding a new job
> add new people - alfan fauzy

- src/data/people.js
> add new people - abdullah ammar

- .gitignore
- README.md
- package.json
- playwright.config.js
- pnpm-lock.yaml
- src/routes/+layout.svelte
- src/routes/+page.svelte
- tests/home.test.js
- tests/pages/home.page.js
- tests/test.js
this PR contains:
- fix lint
- upgrade playwright & integrate test report
- add some selectors ID
- implement [Page-Object-Model](https://martinfowler.com/bliki/PageObject.html)
- add more test
> playwright test improvement
